# Generated by Django 4.0.2 on 2022-02-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='brewery',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer',
            name='profile',
            field=models.CharField(default='empty', max_length=50),
            preserve_default=False,
        ),
    ]
